### ISSUE TITLE
App and master protocols swapped with custom protocols file

### ISSUE THREAD

**Issue by simonemainardi** [ntop/nDPI#644] opened 2018-11-29 07:34 UTC
```
simone@devel:~/ntopng$ cat /tmp/proto
tcp:3000@NTOP
simone@devel:~/ntopng$ sudo ./ntopng -i eno1 --disable-login 1 --dont-change-user --ndpi-protocols /tmp/proto
```

![image](https://user-images.githubusercontent.com/3397663/49206180-8f13ca80-f3b1-11e8-8c6b-f801865a2304.png)

I'm posting here as I've verified that protocols arrive exchanged from nDPI.

**Comment by utoni** [comment] 2022-07-04 08:45
Is this issue still valid? If so, I would appreciate a PCAP.

**Comment by IvanNardi** [comment] 2024-09-07 09:59
Closing; not able to reproduce the issue.

**Closed as completed by IvanNardi** 2024-09-07 09:59 UTC
Labels: bug
