### ISSUE TITLE
make error:unknown type name ‘json_object’

### ISSUE THREAD

**Issue by ghost** [ntop/nDPI#414] opened 2017-06-25 04:23 UTC
a error while making:
......
ndpiReader.c: In function ‘bpf_filter_produce_filter’:
ndpiReader.c:2310:3: error: unknown type name ‘json_object’
   json_object *jObj_bpfFilter = json_object_new_object();
   ^
......
thx

**Comment by YumingMa** [comment] 2017-06-25 08:49
I met the same error. the error was caused by 7235c9a7.

**Comment by kYroL01** [comment] 2017-06-26 10:16
Let me know if the error is fixed now

**Closed as completed** 2017-06-26 10:39 UTC

**Comment by ghost** [comment] 2017-06-26 10:40
nice work,it works:)
