### ISSUE TITLE
np. iil

### ISSUE THREAD

**Issue by FelineAsshole** [ntop/nDPI#2493] opened 2024-07-11 05:03 UTC
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I always need to [...]

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
p i hp

**Comment by utoni** [comment] 2024-07-11 09:52
Could you please elaborate what the issue is you're experiencing?
Closing this issue. Please reopen after providing more information.

**Closed as completed by utoni** 2024-07-11 09:52 UTC
Labels: enhancement
