### ISSUE TITLE
Some of nDPI filters do not match traffic

### ISSUE THREAD

**Issue by Mile-Lile** [ntop/nDPI#22] opened 2015-06-08 12:08 UTC
I am ddwrt user and some time ago ddwrt developers drop using l7 filters and started using nDPI with iptables (for marking-matching traffic for QoS and Access Restriction purposes). I am not developer nor the network guru. Just simple SOHO user with very basic understanding of routers.
ddwrt has big community and now we have problem because some nDPI protocols (filters) do not work. ddwrt devs says it is not ddwrt problem. Youtube, Steam do not work... my findings about this problem are here in bug report on ddwrt TRAC http://svn.dd-wrt.com/ticket/4117#comment:7
If I can provide more informations I would be happy, just to solve this issue. Thx for your work on nDPI it is already great!

**Comment by lucaderi** [comment] 2015-06-10 14:33
@Mile-Lile Can you please attach a pcap file that I can use to reproduce the bug?

**Comment by Mile-Lile** [comment] 2015-06-10 17:20
I can run Wireshark on Windows machine and get you pcap but I think it wont help much because nDPI is implemented and running as module on ddwrt router (my win machine is behind that router)... it is embedded system and there is no flashspace for tcpdump (at least on my router, no space for optware - cheap low end router)... Recently I found out that ddwrt nDPI work is based on this "distro" of nDPI http://devel.aanet.ru/ndpi/

**Comment by Mile-Lile** [comment] 2015-06-10 18:35
ok. here is pcap. You will see (line 660) that I successfully connected to youtube (tls1) but skype after upgrade of app failed to connect and did retransmision all the time... file is 12,4MB so it is on gdrive for download https://drive.google.com/file/d/0B0SCwy1irn3qR0VKVlJRMGRBMUE/view?usp=sharing
here is ddwrt firewall where you can see that skype and youtube filters are loaded but aperently only skype is working http://www.dodaj.rs/f/3q/74/VkSNqDL/ddwrtfirewall.png

**Comment by Mile-Lile** [comment] 2015-06-10 18:38
File is to big for upload 12.4MB and only 10MB is allowed on git so here is my googledrive where you can download it  <https://drive.google.com/file/d/0B0SCwy1irn3qR0VKVlJRMGRBMUE/view?usp=sharing> https://drive.google.com/file/d/0B0SCwy1irn3qR0VKVlJRMGRBMUE/view?usp=sharing

**Comment by lucaderi** [comment] 2015-06-15 14:23
@Mile-Lile I have looked at the traffic and I believe nDPI works correctly. I think the issue is because you use an old nDPI. In order to update I need somebody to send me the patches I need to include into the linux kernel module for nDPI. Please try to send me a merge request.

**Comment by Mile-Lile** [comment] 2015-06-15 17:07
Not sure that I understand what I have to do? ddwrt uses latest 1.60 nDPI, and kernles 3.10, 3.18, 3.19, 4.1 depending on unit... I would send you the "patches" but I don't know anything about coding and programing. I am not developer. Just SOHO user on ddwrt non comercial community .What about Humberto, he told me that he will do some patches for kernel and netfilter till last Sunday...

**Comment by betolj** [comment] 2015-06-16 02:10
The "ndpi-netfilter" projects with logical structure based on "ewildgoose" model don't  work well nowadays. 

1. Only one exclusive "conntrack notify" call: For this reason, it cann't be used in conjunction with nfnetlink. But, when you remove the nfnetlink kernel module, the conntrack application wont works anymore.

2. The web host detection depends on http or ssl protocols enabled: Youtube or Facebook protocols are not external modules (like /usr/src/nDPI/src/lib/protocols/*).

I finished xt_ndpi fixes today:
- Remove "conntrack notifier" from source code and include a new ndpi flow garbage collector for 3.x kernel series. Now, no longer need remove the nfnetlink kernel module to install xt_ndpi.
- Enable http and ssl protocol for youtube, facebook and others.

My tests, showed satisfactory results.
https://github.com/betolj/ndpi-netfilter

**Comment by Mile-Lile** [comment] 2015-06-16 03:16
Thx betolj!!!

**Comment by vel21ripn** [comment] 2015-06-16 07:44
On what traffic you tested? I was getting consistently "out of memory" on the traffic of 200 Mbit / s 120k conntrack after 4-8 hours (conntack callback patch).
I have a version without the patch to the kernel, but it requires a the kernel 3.10 and above. Part of my corrections were included in nDPI, but then the process is stopped. Look http://devel.aanet.ru/ndpi/. Translation into English by http://translate.google.com

**Comment by betolj** [comment] 2015-06-16 11:19
Hi, vel21ripn.

Your tests are made with http://devel.aanet.ru/ndpi/ ?

From 3.2 kernel series, the kernel patch is necessary because the register of "conntrack notify event" is exclusive (only one). And this is made by nfnetlink (default) call - It is mandatory requirement to use conntrack and conntrackd tools. So, the purpose of kernel patch is to allow two simultaneously conntrack notify events - to discover which connections were destroyed and free ndpi flow maps. Or change base code for "nf_ct_extend_custom_register" call (kernel >= 3.10).

The changes that I made is *based* on "ewildgoose" project. I preferred to opt for a solution based on a simple garbage collector (gc_timeout). So, i include a detection flow timeout of 30s and connection flow timeout of 180s. And for each new flow mapping, i made a search flow and check the timouts. It is more simple and different from the proposal of "http://devel.aanet.ru/ndpi/" project.

My tests, showed satisfactory results.
The changes are recent and i'm evaluating.
https://github.com/betolj/ndpi-netfilter

**Comment by vel21ripn** [comment] 2015-06-17 07:55
Yes, I use this version for almost a year. Version "ewildgoose" contains a memory leak or a "race condition" or problems with locks. The second "callback" and duplication nf_conntrack - bad idea.
I added the extension "nf_conntrack" (for older kernels require a patch). Main goals: reducing the required memory (850 bytes per connection), stable performance, support for IPv6.

**Comment by betolj** [comment] 2015-06-17 11:04
Ok. Just now I understand that you are the developer in "devel.aanet.ru".
I will give a better studied in your solution too and and try to improve my code too.

I could enable the youtube, facebook and others web hosts filtering with something like this:

static u8 nfndpi_protocols_http[NDPI_LAST_IMPLEMENTED_PROTOCOL];
...
ndpi_enable_protocols (const struct xt_ndpi_mtinfo*info)
{
...
                        spin_lock_bh (&ipq_lock);
                        ...
                        if (nfndpi_protocols_http[i]) {
                           NDPI_ADD_PROTOCOL_TO_BITMASK(protocols_bitmask, 7);
                           NDPI_ADD_PROTOCOL_TO_BITMASK(protocols_bitmask, 91);
                        }
                        atomic_inc...
...
}
static int __init ndpi_mt_init(void)
{
...
        for (i = 0; i < NDPI_LAST_IMPLEMENTED_PROTOCOL; i++){
                atomic_set (&protocols_cnt[i], 0);
                if ((i > 118 && i < 127) || (i > 139 && i < 146) || (i > 175 && i < 182 ) || i == 70 || i == 133) nfndpi_protocols_http[i]=1;
                else nfndpi_protocols_http[i]=0;
        }
...
}

The web hosts filtering is working now (youtube,facebook...).
But some times the system doesn't detect correctly multiple connections (any protocol).

**Comment by lucaderi** [comment] 2015-06-21 20:53
@betolj @vel21ripn @Mile-Lile Ok guys but can you please send me a merge request so I can integrate all this into nDPI?

**Comment by lucaderi** [comment] 2015-07-01 16:17
@betolj @vel21ripn @Mile-Lile Hi all unless you send us a merge request soon, we're going to close this issue.

**Comment by lucaderi** [comment] 2015-07-13 13:37
Closing the issue as we have not received a merge request yet. Once this will happen we will reopen it.

**Closed by lucaderi** 2015-07-13 13:37 UTC

**Comment by ver2go** [comment] 2015-08-04 00:55
I'm seeing this issue too and would like to be able to filter on YouTube.  So you need @Mile-Lile @betolj @vel21ripn to submit a merge before it can be fixed?

**Comment by kYroL01** [comment] 2015-08-04 08:27
@ver2go If you think you solve the problem, please, send a pull request, so we can see the result of your fixing. We cannot discuss about a problem without seeing the code.
Thank you.
