### ISSUE TITLE
Live detection

### ISSUE THREAD

**Issue by imehrdad2012** [ntop/nDPI#100] opened 2015-10-08 01:23 UTC
Hi,

Thanks for providing the useful DPI library.  I am interested in live DPI but I would like to know the application name as soon as I observe the first few packets in the flow to drop the flow before it gets completed. Do you have any pointers on how to achieve this goal based on the example provided? 

Sorry in advance if I am opening an issue since I could not find the mailing list.

**Comment by kYroL01** [comment] 2015-10-08 16:10
Hello.
nDPI use these ways:
1) Application protocol based on UDP could be detected with 2 packets;
2) Application protocol based on TCP could be detected with 15 packets;
3) If no app proto could be detecting, is marked as "Unknown".

You can't specify how many packets captured, but you can use the **_-s**_ option, that define the capture duration in second (availlable only in live mode).

I close this issue, but if you have other questions or also have featured to proposed, ask or open a proposal issue, ok ?

**Closed as completed by kYroL01** 2015-10-08 16:10 UTC

**Comment by mehrdadmoradi-crusoe** [comment] 2015-10-08 16:18
Thanks for the response. Is there any way to understand the TCP application protocol by observing fewer than 15 packets? My traffic is mostly short-lived TCP flows so it is necessary for me decide to pass or the drop traffic faster.

**Comment by kYroL01** [comment] 2015-10-08 16:49
Unfortunately not yet.
I think your question is kinda in discussion in this other issue https://github.com/ntop/nDPI/issues/85.
So the question is open, as you can see.

**Comment by mehrdadmoradi-crusoe** [comment] 2015-10-08 18:56
Sure. 

The only thing I was able to find in the source code is the following that defines when to give up inspecting a flow. Right?
  if((flow->detected_protocol.protocol != NDPI_PROTOCOL_UNKNOWN)
     || ((proto == IPPROTO_UDP) && (flow->packets > 8))
     || ((proto == IPPROTO_TCP) && (flow->packets > 10))) {
    flow->detection_completed = 1;

Unlike the number 2 and 15 you mentioned, it seems the TCP threshold is set to 10 and UDP one to 8.
I would be happy to provide application-specific flexibility in when to stop inspecting a flow and then contribute back.

Best Regards,
—Mehrdad

**Comment by kYroL01** [comment] 2015-10-10 09:03
Yes, you're right, but it's not a strictly rule. For example, a DNS packet could be detected just with a single packet (you can try). So it depends on the application protocol to be detect.

**Comment by lucaderi** [comment] 2015-10-10 09:04
This issue is a duplicate of #85
