### ISSUE TITLE
Creating PCAP.OUT file in tests/result

### ISSUE THREAD

**Issue by Douina** [ntop/nDPI#1224] opened 2021-07-01 14:37 UTC
Hello, i I had already created new protocol for MPEG-DASH application , by following steps :[https://github.com/ntop/nDPI/commit/1c2a0c36f130baa5eac1548d97da8553510849b3]  ,but nDPI stills don't know it , maybe because of i had not create dash.pcap.out file? then how to create it ? please i need help

**Comment by utoni** [comment] 2021-07-01 20:26
The `dash.pcap.out` will get created by `tests/do.sh`. But before executing this script, you need to place `dash.pcap` in `tests/pcap/`.

You can also `example/ndpiReader -i [path-to-dash.pcap]` to see if your protocol detection works. You can use the argument `-v2` as well to print some more detailed information.

**Comment by Douina** [comment] 2021-07-03 12:02
thanks for reply @lnslbrty , when i run `tests/do.sh` it show me :
` Unable to write in file result/dash.pcap.out: quitting`
do you know where is the problem ?

**Comment by utoni** [comment] 2021-07-04 10:45
The file `result/dash.pcap.out` could not be opened for writing. Is your filesystem read-only?

**Comment by Douina** [comment] 2021-07-04 11:45
@lnslbrty it's oky now , i had just add sudo to `sudo ./do.sh` , and that's the result of dash.pcap.out file 
`HTTP	4701	62789812	109
Microsoft	56	16974	5
JA3 Host Stats: 
		 IP Address                  	 # JA3C     
	1	 10.0.2.15                	 2      
	1	TCP 10.0.2.15:35064 <-> 10.0.2.15:80 [proto: 260.7/DASH.HTTP][cat: Web/5][26 pkts/2206 bytes <-> 38 pkts/1082420 bytes][Goodput ratio: 8/100][0.69 sec][Host: example.com][bytes ratio: -0.996 (Download)][IAT c2s/s2c min/avg/max/stddev: 0/0 2/0 42/1 9/0][Pkt Len c2s/s2c min/avg/max/stddev: 76/76 85/28485 262/32856 36/11063][URL: example.com/1sec/bunny_4726737bps/BigBuckBunny_1s80.m4s][StatusCode: 0][User-Agent: Lavf/58.45.100][PLAIN TEXT (GET /1sec/bunny)][Plen Bins: 0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,97]`

because when i run this cmd its show me that is  just MPEG protocol and not DASH protocol

`nDPI Memory statistics:
	nDPI Memory (once):      104.60 KB    
	Flow Memory (per flow):  1.91 KB      
	Actual Memory:           1.82 MB      
	Peak Memory:             1.82 MB      

Traffic statistics:
	Ethernet bytes:        9648848       (includes ethernet CRC/IFC/trailer)
	Discarded bytes:       0            
	IP packets:            733           of 733 packets total
	IP bytes:              9631256       (avg pkt size 13139 bytes)
	Unique flows:          20           
	TCP Packets:           733          
	UDP Packets:           0            
	VLAN Packets:          0            
	MPLS Packets:          0            
	PPPoE Packets:         0            
	Fragmented Packets:    0            
	Max Packet size:       32820        
	Packet Len < 64:       410          
	Packet Len 64-128:     0            
	Packet Len 128-256:    20           
	Packet Len 256-1024:   1            
	Packet Len 1024-1500:  3            
	Packet Len > 1500:     299          
	nDPI throughput:       42.66 pps / 4.28 Mb/sec
	Traffic throughput:    42.66 pps / 4.28 Mb/sec
	Traffic duration:      17.181 sec
	Guessed flow protos:   0            


Detected protocols:
	MPEG                 packets: 733           bytes: 9631256       flows: 20           


Protocol statistics:
	Fun                        9631256 bytes`
have you any idea about this ?

**Comment by utoni** [comment] 2021-07-04 12:03
I need to read your code to give you an answer. :)

**Comment by Douina** [comment] 2021-07-04 12:31
@lnslbrty  when i run `sudo ndpiReader -i tests/pcap/dash.pcap -v2 ` : 
`Detected protocols:
	MPEG                 packets: 4701          bytes: 62789812      flows: 109          
	Microsoft            packets: 56            bytes: 16974         flows: 5            
Protocol statistics:
	Acceptable                   16974 bytes
	Fun                       62789812 bytes

	1	TCP 10.0.2.15:34886 <-> 10.0.2.15:80 [proto: 42/MPEG][9 pkts/2598 bytes][Host: example.com]
	2	TCP 10.0.2.15:34888 <-> 10.0.2.15:80 [proto: 42/MPEG][11 pkts/2273 bytes][Host: example.com]
`
me i want to show DASH instead of MPEG,
please help

**Comment by utoni** [comment] 2021-10-06 14:11
possible duplicate of #1223

**Closed as completed by utoni** 2021-10-06 14:11 UTC
Labels: duplicate, Protocols
