### ISSUE TITLE
Wrong detection of LYNC protocol

### ISSUE THREAD

**Issue by ohadkl** [ntop/nDPI#134] opened 2016-01-03 16:49 UTC
We are using nProbe Pro v.7.3.151217 ($Revision: 4740 $) on Ububtu for monitoring IP cameras.
The nDPI detect the Lync protocol but it should detect RTP as the flow is video being sent from the IP camera to a network video recorder.
attached is a link to a pcap file that demonstrates the false detection.

https://dl.dropboxusercontent.com/u/27973370/LYNC%20protocol.pcapng

**Comment by kYroL01** [comment] 2016-01-03 16:59
Thank you for the pcap. I'll try to fix asap !

**Comment by kYroL01** [comment] 2016-01-03 23:08
Hi @ohadkl .
I just launch nDPI with your pcap but i don't see any Lync protocol detected.
Look:
![1d](https://cloud.githubusercontent.com/assets/7222956/12081389/504b829e-b277-11e5-8170-45442fc08567.png)

Are u sure you have the latest nDPI version ?

**Comment by ohadkl** [comment] 2016-01-04 08:05
Hi @kYroL01,
we are using nProbe with one of the latest versions so i assumed it includes also the latest version of nDPI.
I will try and update the package and re-validate.

**Comment by kYroL01** [comment] 2016-01-04 10:36
Please update and let me know, thanks.

**Comment by kYroL01** [comment] 2016-01-12 16:25
@ohadkl Any News ? For me the issue is fixed, but I wanna be sure if I close this or not.

**Comment by ohadkl** [comment] 2016-01-12 21:54
I have tested this issue further more and it seems that the LYNC identification is happening from time to time and not constant. As such it is very hard for me to capture the specific PCAP file.

you can close the case, if i will be able to capture the proper PCAP file i will reopen the case.

**Comment by kYroL01** [comment] 2016-01-13 10:03
Ok, thank you for the answer. If you have any news, re-open the issue.

**Closed as completed by kYroL01** 2016-01-13 10:03 UTC
