### ISSUE TITLE
ndpi detect netflow/ssl anyconnect vpn only by known port ?

### ISSUE THREAD

**Issue by Niko78** [ntop/nDPI#194] opened 2016-05-18 06:59 UTC
hi,
I use last nightly ntopng and ndpi detects strange things
1) all my routers sends netflow to ntopng on port 7002 so should be detected as netflow stream, but it is displayed as afs3-prserver in ntopng
2) we have cisco anyconnect ssl vpn access and this time it appears in ntopng as quic

I'm not saying it's not normal, I just would like to know if it's normal.

thanks

Nico

**Comment by kYroL01** [comment] 2016-05-18 07:38
Can you provide a pcap with specific captured traffic to understand better ?
I don't think is normal, I think it might be a bug in dissection, but I have to check your pcap.

Thanks

**Comment by Niko78** [comment] 2016-05-18 08:01
sure
first pcap about netflow stream received on ntopng server
[netflow.zip](https://github.com/ntop/nDPI/files/269898/netflow.zip)

**Comment by Niko78** [comment] 2016-05-18 08:18
second pcap about stream being anyconnect ssl vpn
[anyconnect.zip](https://github.com/ntop/nDPI/files/269934/anyconnect.zip)

**Comment by kYroL01** [comment] 2016-05-18 08:24
@Niko78 for point **1**: I passed the pcap on nDPI and it detect perfectly as Netflow.
The problem is that ntopng show only 10 pkts as Netflow, and the rest as RX or Unknown.
The _afs3-prserver_ is the keyword associated by the web to port [7002](http://www.t1shopper.com/tools/port-number/7002/)

**Comment by kYroL01** [comment] 2016-05-18 08:29
Point **2**: nDPI detect correctly this pcap as SSL and OpenVPN. No errors. So try to upgrade nDPI and ntopng and recheck.

**Comment by Niko78** [comment] 2016-05-18 08:29
ah ok and what could be the solution ?

**Comment by kYroL01** [comment] 2016-05-18 08:31
I think is a things internal to ntopng and nDPI could be not well syncronized. We have to check better.
I suggest first to upgrade all and try again.

**Comment by Niko78** [comment] 2016-05-18 08:46
just upgraded now I'm in
ntopng 2.3.160518
1.7.1-dev-413-1e37916

**Comment by Niko78** [comment] 2016-05-18 09:37
so after the upgrade, ntopng still shows me QUIC for anyconnect ssl vpn and still afs3-prserver for netflow :-(

**Comment by kYroL01** [comment] 2016-05-18 09:49
This is what I see from anyconnect pcap on ntopng:

![anyconnect](https://cloud.githubusercontent.com/assets/7222956/15354529/74f6e6ba-1cee-11e6-8469-6e575cd09154.png)

**Comment by kYroL01** [comment] 2016-05-18 09:52
and this for netflow:

filtered by Netflow application
![netflow_1](https://cloud.githubusercontent.com/assets/7222956/15354594/bbc11264-1cee-11e6-9606-ff3cd3abde16.png)

and with all protos enabled
![netflow_err](https://cloud.githubusercontent.com/assets/7222956/15354611/c81ab2d6-1cee-11e6-8129-58901fb6ef44.png)

So the problem is that ntopng does not show all the Netflow pkts as netflow, but the afs3-prserver is just the name associated to port 7002, so what's the problem with this ? The coloumn Application is where the flows are detected.

And in nDPI I detect all the protos correctly.

**Comment by Niko78** [comment] 2016-05-18 10:07
ok
just retried on my side
<img width="909" alt="anyconnect" src="https://cloud.githubusercontent.com/assets/17108017/15355058/03be21c2-1cf1-11e6-9999-b347dd23255e.PNG">
<img width="917" alt="netflow" src="https://cloud.githubusercontent.com/assets/17108017/15355059/03be75a0-1cf1-11e6-866c-d645d7a76d09.PNG">

**Comment by kYroL01** [comment] 2016-05-18 10:12
Yes, the error is on RX show for anyconnect, and this is the same for me, but i can't see wrong quic pcap... It's strange. Are u really sure to have upgrade correctly ? Because we did some modification on quic yesterday.

**Comment by Niko78** [comment] 2016-05-18 10:18
well I just upgraded ntopng/nprobe...
<img width="929" alt="ntop" src="https://cloud.githubusercontent.com/assets/17108017/15355387/96972268-1cf2-11e6-8eef-444b288517b1.PNG">

or I missed something else ?

**Comment by kYroL01** [comment] 2016-05-18 19:16
It's very strange. I think you didn't missing anything but I don't understand why I see correctly your pcap and you don't.
I have to investigate much better.

**Comment by Niko78** [comment] 2016-05-21 08:47
if I can help you let me know

**Comment by Niko78** [comment] 2016-05-24 08:34
about netflow appearing as RX
do you think a fix is possible to get netflow instead of RX ?

**Comment by kYroL01** [comment] 2016-05-24 08:37
Yes, sure, later i'll check all.

**Comment by Niko78** [comment] 2016-05-28 18:19
I think I found the issue 
Right now I start ntop like that
ntopng -F "mysql;localhost;ntopng;flows;root;azer" -i tcp://172.31.1.244:5556 -d /storage/tmp -w 3000 -v

if I start it like that 
ntopng -F "mysql;localhost;ntopng;flows;root;azer" -i eth0 -d /storage/tmp -w 3000 -v
it seems to be ok
with this command I can even see throughput graph below whereas it doesn't work with first command

problem is that with second command I can't get all streams, I can see only packets from all my routers (netflow packets )and not trafic, no idea why

hope it will help

Nico

**Comment by kYroL01** [comment] 2016-05-29 11:01
@Niko78 It seems more a ntopng/nprobe issue than a nDPI issue, because as I explained before, with nDPI I have detected the traffic correctly.

**Comment by Niko78** [comment] 2016-05-29 12:29
ok, I posted an issue in ntopng with a link to here
let's see what they think about

**Comment by lucaderi** [comment] 2016-05-31 10:26
I have looked at the packets and in particular to fragments that create the issue you reported. In nDPIreader fragments are dropped, in ntopng they are handled. I have made an enhancement to nDPIreader and nDPI, so issues should be fixed. This said you have most of the traffic fragmented so IMHO you should fix your network first.

**Closed as completed by lucaderi** 2016-05-31 10:26 UTC
Labels: bug, enhancement, help wanted
