### ISSUE TITLE
Buid failed on FreeBSD

### ISSUE THREAD

**Issue by panaceya** [ntop/nDPI#122] opened 2015-11-26 06:58 UTC
Hello!

I have error in compilation nDPI:

```
libtool: compile:  cc -DHAVE_CONFIG_H -I. -I../.. -I../../src/include/ -I../../src/lib/third_party/include/ -g -O2 -fPIC -DPIC -MT protocols/libndpi_la-tcp_udp.lo -MD -MP -MF protocols/.deps/libndpi_la-tcp_udp.Tpo -c protocols/tcp_udp.c  -fPIC -DPIC -o protocols/.libs/libndpi_la-tcp_udp.o
protocols/tcp_udp.c:34:18: error: use of undeclared identifier 'IPPROTO_UDP'
  if(protocol == IPPROTO_UDP) {
                 ^
1 error generated.
*** Error code 1

Stop.
make[2]: stopped in /tmp/nDPI/src/lib
*** Error code 1

Stop.
make[1]: stopped in /tmp/nDPI
*** Error code 1

Stop.
make: stopped in /tmp/nDPI
```

OS: FreeBSD 10.2

**Comment by kYroL01** [comment] 2015-11-26 11:16
Which version of nDPI are you using ?
Have you update from stable or dev branch ?

Tell me if this fix 12b47fece04ba658227790d7fbe76624bd21984e solved the problem (update from dev branch).

**Comment by panaceya** [comment] 2015-11-26 21:16
I use latest version from git (origin/dev).

**Comment by kYroL01** [comment] 2015-11-26 21:19
Ok, with that fix, the issue is solved ? update and let me know, thanks.

**Comment by panaceya** [comment] 2015-11-27 08:23
Sorry, but error exists:

```
/bin/sh ../../libtool  --tag=CC   --mode=compile cc -DHAVE_CONFIG_H -I. -I../..  -I../../src/include/  -I../../src/lib/third_party/include/   -g -O2  -fPIC -DPIC -MT protocols/libndpi_la-syslog.lo -MD -MP -MF protocols/.deps/libndpi_la-syslog.Tpo -c -o protocols/libndpi_la-syslog.lo `test -f 'protocols/syslog.c' || echo './'`protocols/syslog.c
libtool: compile:  cc -DHAVE_CONFIG_H -I. -I../.. -I../../src/include/ -I../../src/lib/third_party/include/ -g -O2 -fPIC -DPIC -MT protocols/libndpi_la-syslog.lo -MD -MP -MF protocols/.deps/libndpi_la-syslog.Tpo -c protocols/syslog.c  -fPIC -DPIC -o protocols/.libs/libndpi_la-syslog.o
libtool: compile:  cc -DHAVE_CONFIG_H -I. -I../.. -I../../src/include/ -I../../src/lib/third_party/include/ -g -O2 -fPIC -DPIC -MT protocols/libndpi_la-syslog.lo -MD -MP -MF protocols/.deps/libndpi_la-syslog.Tpo -c protocols/syslog.c -o protocols/libndpi_la-syslog.o >/dev/null 2>&1
mv -f protocols/.deps/libndpi_la-syslog.Tpo protocols/.deps/libndpi_la-syslog.Plo
/bin/sh ../../libtool  --tag=CC   --mode=compile cc -DHAVE_CONFIG_H -I. -I../..  -I../../src/include/  -I../../src/lib/third_party/include/   -g -O2  -fPIC -DPIC -MT protocols/libndpi_la-tcp_udp.lo -MD -MP -MF protocols/.deps/libndpi_la-tcp_udp.Tpo -c -o protocols/libndpi_la-tcp_udp.lo `test -f 'protocols/tcp_udp.c' || echo './'`protocols/tcp_udp.c
libtool: compile:  cc -DHAVE_CONFIG_H -I. -I../.. -I../../src/include/ -I../../src/lib/third_party/include/ -g -O2 -fPIC -DPIC -MT protocols/libndpi_la-tcp_udp.lo -MD -MP -MF protocols/.deps/libndpi_la-tcp_udp.Tpo -c protocols/tcp_udp.c  -fPIC -DPIC -o protocols/.libs/libndpi_la-tcp_udp.o
protocols/tcp_udp.c:34:18: error: use of undeclared identifier 'IPPROTO_UDP'
  if(protocol == IPPROTO_UDP) {
                 ^
1 error generated.
*** Error code 1

Stop.
make[2]: stopped in /tmp/nDPI/src/lib
*** Error code 1

Stop.
make[1]: stopped in /tmp/nDPI
*** Error code 1

Stop.
make: stopped in /tmp/nDPI
```

```
git rev-list --tags --max-count=1
a31b0a3354d4a6f62ea9c338ed6f890136f1d3e6
```

**Comment by kYroL01** [comment] 2015-11-27 15:55
I'm doing some modifies. Please wait.
Thank you

**Comment by lucaderi** [comment] 2015-11-28 07:44
@kYroL01 @panaceya Due to windows (where I had the same problem) I have made some changes a day ago. Please do not change anything and try again first.

**Comment by kYroL01** [comment] 2015-11-28 13:04
@lucaderi Yes Luca, I saw the modification. For me all working correctly. We're waiting an answer after @panaceya test.

**Comment by kYroL01** [comment] 2015-11-30 15:04
Please @panaceya tell us if the recent changes solved the problem, so we can close this issue.
Thank you.

**Comment by panaceya** [comment] 2015-11-30 20:44
Sorry, I could not answer before. Now there are no errors. 
Thanks for the work and have a nice day :)

**Closed as completed** 2015-11-30 20:44 UTC

**Comment by kYroL01** [comment] 2015-12-01 12:52
Great. Thank you
